enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[YouTube]
included-patches = "'Custom branding'"
excluded-patches = "'Swipe controls'"
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
version = "auto"
arch = "arm64-v8a"

[Tiktok]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
excluded-patches = "'SIM spoof'"
version = "auto"

[Twitter]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
apkmirror-dpi = "120-640dpi"
build-mode = "apk"
version = "auto"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
version = "auto"

