enable-magisk-update = true
parallel-jobs = 1
compression-level = 9
remove-rv-integrations-checks = true

patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
rv-brand = "by h1toru"

#===== app config =====#

[YouTube-Premium]
enabled = true
app-name = "YouTube Premium"
# rv-brand = "Extended"
build-mode = "apk"
version = "auto"
arch = "both"
riplib = true
module-prop-name = "h1toru-rvm-yt"

patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
patcher-args = """\
  -e 'Change version code' \
  -e 'Custom branding name for YouTube' -OappName='YouTube Premium' \
  -d 'Custom branding icon for YouTube' \
  -e 'GmsCore support' -OpackageNameYouTube='h1toru.rvm.yt' \
  -e 'Settings for YouTube' -OrvxSettingsLabel='Extended' \
  -e 'Return YouTube Username' \
  -d 'Enable gradient loading screen' \
  -d 'Alternative thumbnails' \
  -d 'Enable debug logging' \
  """

apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
#uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Premium-Module]
enabled = true
app-name = "YouTube Premium"
# rv-brand = "Extended"
build-mode = "module"
version = "auto"
arch = "all"
riplib = true
module-prop-name = "h1toru-rvm-yt"

patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
patcher-args = """\
  -e 'Change version code' \
  -e 'Custom branding name for YouTube' -OappName='YouTube Premium' \
  -d 'Custom branding icon for YouTube' \
  -e 'GmsCore support' -OpackageNameYouTube='h1toru.rvm.yt' \
  -e 'Settings for YouTube' -OrvxSettingsLabel='Extended' \
  -e 'Return YouTube Username' \
  -d 'Enable gradient loading screen' \
  -d 'Alternative thumbnails' \
  -d 'Enable debug logging' \
  """

apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
#uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Extended]
enabled = true
app-name = "YouTube Extended"
# rv-brand = "Extended"
build-mode = "apk"
version = "auto"
arch = "both"
riplib = true
module-prop-name = "h1toru-rvm-yt"

patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
patcher-args = """\
  -e 'Change version code' \
  -e 'Custom branding name for YouTube' -OappName='YouTube Extended' \
  -e 'Custom branding icon for YouTube' -OappIcon='mmt' \
  -e 'GmsCore support' -OpackageNameYouTube='h1toru.rvm.yt.ex' \
  -e 'Settings for YouTube' -OrvxSettingsLabel='Extended' \
  -e 'Return YouTube Username' \
  -d 'Enable gradient loading screen' \
  -d 'Alternative thumbnails' \
  -d 'Enable debug logging' \
  """

apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
#uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Extended-Module]
enabled = true
app-name = "YouTube Extended"
# rv-brand = "Extended"
build-mode = "both"
version = "auto"
arch = "all"
riplib = true
module-prop-name = "h1toru-rvm-yt"

patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
patcher-args = """\
  -e 'Change version code' \
  -e 'Custom branding name for YouTube' -OappName='YouTube Extended' \
  -e 'Custom branding icon for YouTube' -OappIcon='mmt' \
  -e 'GmsCore support' -OpackageNameYouTube='h1toru.rvm.yt.ex' \
  -e 'Settings for YouTube' -OrvxSettingsLabel='Extended' \
  -e 'Return YouTube Username' \
  -d 'Enable gradient loading screen' \
  -d 'Alternative thumbnails' \
  -d 'Enable debug logging' \
  """

apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
#uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YTMusic-Premium]
enabled = true
app-name = "YTMusic Premium"
# rv-brand = "Extended"
build-mode = "both"
version = "auto"
arch = "both"
riplib = true
module-prop-name = "h1toru-rvm-ytm"

patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
patcher-args = """\
  -e 'Change version code' \
  -e 'Custom branding name for YouTube Music' -OappNameLauncher='YouTube Music Premium' -OappNameNotification='YTMusic Premium' \
  -d 'Custom branding icon for YouTube Music' \
  -e 'GmsCore support' -OpackageNameYouTubeMusic='h1toru.rvm.ytm' \
  -e 'Settings for YouTube Music' -OrvxSettingsLabel='Extended' \
  -e 'Disable music video in album' \
  -e 'Return YouTube Username' \
  -d 'Enable debug logging' \
  """

apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
#uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[YTMusic-Extended]
enabled = true
app-name = "YTMusic Extended"
# rv-brand = "Extended"
build-mode = "both"
version = "auto"
arch = "both"
riplib = true
module-prop-name = "h1toru-rvm-ytm"

patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
patcher-args = """\
  -e 'Change version code' \
  -e 'Custom branding name for YouTube Music' -OappNameLauncher='YouTube Music Extended' -OappNameNotification='YTMusic Extended' \
  -e 'Custom branding icon for YouTube Music' -OappIcon='mmt' \
  -e 'GmsCore support' -OpackageNameYouTubeMusic='h1toru.rvm.ytm.ex' \
  -e 'Settings for YouTube Music' -OrvxSettingsLabel='Extended' \
  -e 'Disable music video in album' \
  -e 'Return YouTube Username' \
  -d 'Enable debug logging' \
  """

apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
#uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
